### ISSUE TITLE
How can I get the "detectannotmass.txt" which is written in the "visinbreast.m" code,

### ISSUE THREAD

**Issue by ljy1758159924** [wentaozhu/inbreast#1]
it is the detection box of mass which can be acquired from the contour annotation (min_x, max_x, min_y, max_y for the current mass).,but,How can I acquire the detection box of mass and the .txt files? Should I transfer the .xml files to .txt files in order to acquire the detection box of mass?

**Comment by wentaozhu** [comment]
There is annotation contour in the .xml. You may have a try to parse it and get the max_x, min_x, min_y and max_y

**Comment by jasminjahanpuspo** [comment]
@wentaozhu Thanks for your great work. But I can't get about your "detectannotmass.txt" file which is written in the "visinbreast.m". I am a beginner so it's tough to get this. 
Can you explain to me elaborately how to code this?

**Comment by wentaozhu** [comment]
You can parse the annotation contour in the .xml using https://github.com/wentaozhu/inbreast/blob/master/readxml.m

**Comment by jasminjahanpuspo** [comment]
Thanks for your quick reply. 
But still, I can't get it.  Because I cant understand what the annotation contour means. Here I only have a .xml file in the dataset folder.

**Comment by wentaozhu** [comment]
You can try to use https://github.com/wentaozhu/inbreast/blob/master/readxml.m to parse the xml and get the max_x, min_x, min_y and max_y

**Comment by jasminjahanpuspo** [comment]
Sorry for the late reply. Now I got your point and solved my problems. Thanks for your help.
